# Generated by Django 5.2.17 on 2026-08-20 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='medicine',
            new_name='medicines_m_name_61a774_idx',
            old_name='medicines_m_name_3f8c2a_idx',
        ),
        migrations.RenameIndex(
            model_name='medicineinsuranceprice',
            new_name='medicines_m_generic_09e08f_idx',
            old_name='medicines_m_generic_7a1b2c_idx',
        ),
    ]
