# Generated by Django 5.2.17 on 2026-08-19 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.DecimalField(decimal_places=4, max_digits=24)),
                ('utilized_amount', models.DecimalField(decimal_places=4, default=0, max_digits=24)),
                ('expiry', models.DateField()),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='borrowed_facilities', to='organizations.organization')),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lent_facilities', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='FacilityReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=24)),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='facilities.facility')),
            ],
        ),
    ]
