# Generated by Django 5.2.17 on 2026-08-19 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='facilityreservation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='facilityreservation',
            name='idempotency_key',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='facility',
            constraint=models.CheckConstraint(condition=models.Q(('limit__gt', 0)), name='facility_limit_positive'),
        ),
        migrations.AddConstraint(
            model_name='facility',
            constraint=models.CheckConstraint(condition=models.Q(('utilized_amount__gte', 0)), name='facility_utilized_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='facility',
            constraint=models.CheckConstraint(condition=models.Q(('utilized_amount__lte', models.F('limit'))), name='facility_utilized_within_limit'),
        ),
        migrations.AddConstraint(
            model_name='facility',
            constraint=models.CheckConstraint(condition=models.Q(('lender', models.F('borrower')), _negated=True), name='facility_parties_differ'),
        ),
        migrations.AddConstraint(
            model_name='facilityreservation',
            constraint=models.UniqueConstraint(fields=('facility', 'created_by', 'idempotency_key'), name='unique_facility_reservation_key'),
        ),
    ]
