# Generated by Django 5.2.17 on 2026-08-19 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='idempotencyrecord',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='idempotencyrecord',
            name='operation',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='idempotencyrecord',
            name='request_hash',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='idempotencyrecord',
            name='key',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='idempotencyrecord',
            constraint=models.UniqueConstraint(fields=('actor', 'operation', 'key'), name='unique_idempotency_request'),
        ),
    ]
