# Generated by Django 5.2.17 on 2026-08-19 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=50)),
                ('storage_key', models.CharField(max_length=500, unique=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('checksum_sha256', models.CharField(blank=True, max_length=64)),
                ('scan_status', models.CharField(choices=[('pending', 'در انتظار'), ('clean', 'سالم'), ('infected', 'آلوده')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
