# Generated by Django 5.2.17 on 2026-08-20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("facilities", "0002_facilityreservation_created_by_and_more"),
        ("invoices", "0002_invoice_invoice_amount_positive_and_more"),
        ("organizations", "0002_backfill_role_scopes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancingQuote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("principal", models.DecimalField(decimal_places=4, max_digits=24)),
                ("term_days", models.PositiveIntegerField()),
                ("financing_fee", models.DecimalField(decimal_places=4, max_digits=24)),
                ("platform_fee", models.DecimalField(decimal_places=4, max_digits=24)),
                ("net_amount", models.DecimalField(decimal_places=4, max_digits=24)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FinancingQuoteInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="invoices.invoice"
                    ),
                ),
                (
                    "quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice_lines",
                        to="financing.financingquote",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="financingquote",
            name="invoices",
            field=models.ManyToManyField(
                related_name="financing_quotes",
                through="financing.FinancingQuoteInvoice",
                to="invoices.invoice",
            ),
        ),
        migrations.CreateModel(
            name="FinancingQuoteLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("principal", "اصل مبلغ"),
                            ("financing_fee", "هزینه تأمین مالی"),
                            ("platform_fee", "کارمزد پلتفرم"),
                            ("net_amount", "مبلغ خالص"),
                        ],
                        max_length=24,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=4, max_digits=24)),
                (
                    "quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="financing.financingquote",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FinancingRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("requested_amount", models.DecimalField(decimal_places=4, max_digits=24)),
                ("term", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("quoted", "قیمت‌گذاری‌شده"),
                            ("requested", "درخواست‌شده"),
                            ("approved", "تأییدشده"),
                            ("rejected", "ردشده"),
                            ("disbursed", "پرداخت‌شده"),
                        ],
                        default="quoted",
                        max_length=16,
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approved_financing_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "bank_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="financing_requests",
                        to="organizations.bankaccount",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_financing_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="financing_requests",
                        to="facilities.facility",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="financing_requests",
                        to="invoices.invoice",
                    ),
                ),
                (
                    "quote",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="request",
                        to="financing.financingquote",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FinancingRequestHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        choices=[
                            ("quoted", "قیمت‌گذاری‌شده"),
                            ("requested", "درخواست‌شده"),
                            ("approved", "تأییدشده"),
                            ("rejected", "ردشده"),
                            ("disbursed", "پرداخت‌شده"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("quoted", "قیمت‌گذاری‌شده"),
                            ("requested", "درخواست‌شده"),
                            ("approved", "تأییدشده"),
                            ("rejected", "ردشده"),
                            ("disbursed", "پرداخت‌شده"),
                        ],
                        max_length=16,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="financing.financingrequest",
                    ),
                ),
            ],
            options={"ordering": ("created_at", "pk")},
        ),
        migrations.CreateModel(
            name="Policy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("version", models.PositiveIntegerField(unique=True)),
                ("annual_rate", models.DecimalField(decimal_places=6, max_digits=9)),
                ("platform_fee_rate", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "platform_fee_flat",
                    models.DecimalField(decimal_places=4, default=0, max_digits=24),
                ),
                ("effective_from", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "policies",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("annual_rate__gte", 0)),
                        name="policy_annual_rate_nonnegative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("platform_fee_rate__gte", 0)),
                        name="policy_platform_rate_nonnegative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("platform_fee_flat__gte", 0)),
                        name="policy_platform_flat_nonnegative",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("is_active",),
                        name="unique_active_financing_policy",
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="financingquote",
            name="policy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="quotes",
                to="financing.policy",
            ),
        ),
        migrations.AddConstraint(
            model_name="financingquoteinvoice",
            constraint=models.UniqueConstraint(
                fields=("quote", "invoice"), name="unique_invoice_per_financing_quote"
            ),
        ),
        migrations.AddConstraint(
            model_name="financingquoteline",
            constraint=models.UniqueConstraint(
                fields=("quote", "kind"), name="unique_kind_per_financing_quote"
            ),
        ),
        migrations.AddConstraint(
            model_name="financingquoteline",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", 0)),
                name="financing_quote_line_nonnegative",
            ),
        ),
        migrations.AddIndex(
            model_name="financingrequest",
            index=models.Index(
                fields=["status", "created_at"], name="financing_f_status_a24c9c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="financingrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("requested_amount__gt", 0)),
                name="financing_request_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="financingrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("term__gt", 0)), name="financing_request_term_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="financingquote",
            constraint=models.CheckConstraint(
                condition=models.Q(("principal__gt", 0)),
                name="financing_quote_principal_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="financingquote",
            constraint=models.CheckConstraint(
                condition=models.Q(("term_days__gt", 0)),
                name="financing_quote_term_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="financingquote",
            constraint=models.CheckConstraint(
                condition=models.Q(("financing_fee__gte", 0)),
                name="financing_quote_fee_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="financingquote",
            constraint=models.CheckConstraint(
                condition=models.Q(("platform_fee__gte", 0)),
                name="financing_quote_platform_fee_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="financingquote",
            constraint=models.CheckConstraint(
                condition=models.Q(("net_amount__gt", 0)),
                name="financing_quote_net_positive",
            ),
        ),
    ]
