# Generated by Django 5.2.17 on 2026-08-18 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('bank', 'بانک'), ('insurance', 'بیمه'), ('manufacturer', 'تولیدکننده'), ('distributor', 'پخش'), ('pharmacy', 'داروخانه')], max_length=20)),
                ('national_id', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('active', 'فعال'), ('suspended', 'معلق')], default='active', max_length=16)),
                ('risk_tier', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iban', models.CharField(max_length=26)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='UserMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'مالک سازمان'), ('operator', 'اپراتور'), ('approver', 'تأییدکننده'), ('risk_expert', 'کارشناس ریسک'), ('bank_finance', 'مالی بانک'), ('support', 'پشتیبان')], max_length=20)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'organization', 'role'), name='unique_user_org_role')],
            },
        ),
    ]
