# Generated by Django 5.2.17 on 2026-08-20 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_backfill_master_data_scopes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='organizationcontact',
            new_name='organizatio_organiz_ae8e6a_idx',
            old_name='organizatio_organiz_6b0c1b_idx',
        ),
        migrations.RenameIndex(
            model_name='organizationcontact',
            new_name='organizatio_nationa_407407_idx',
            old_name='organizatio_nationa_0d2f1a_idx',
        ),
    ]
